### ISSUE TITLE
Don't insert code as raw text

### ISSUE THREAD

**Issue by Rapster** [primefaces/showcase-facelift#1]
Instead of inserting code using `<pre />` tag, include code just like PFE does (e.g using JSF function `showcase:getFileContent()`). It's much more easy to maintain _(as you don't have to do anything if files are updated really)_

**Comment by Rapster** [comment]
No feedbacks on this? 😢

**Comment by melloware** [comment]
Thumbs up from me!

**Comment by Rapster** [comment]
I pinged the whole team on it, but no answers... So I didn't do more since. But I think it would be a good addition...

P.S: I meant to put that comment here and not in the PR...

**Comment by mertsincan** [comment]
@Rapster and @tandraschko, Users want to see the source code of all classes used in a bean. Exp; http://localhost:8080/showcase/ui/data/datatable/lazy.xhtml

Expected source codes;
lazy.xhtml, LazyView.java, LazyCarDataModel.java, LazySorter.java, Car.java and CarService.java

Is there an easy way to find LazySorter.java? I just couldn't find it. Maybe, I can find it using "new" keyword. Any thought?

**Comment by Rapster** [comment]
Sure, I'll update the showcase. Thanks for reporting

**Comment by mertsincan** [comment]
Ok, please see my changes;
https://github.com/primefaces/showcase-facelift/commit/171c9dd1e66ccae71271801aabe463ea7346972c

We just need to find LazySorter.java.

**Comment by Rapster** [comment]
I like the refactoring, but the actual code should have been able to detect that `Car` has to be included. Anyway, I still like the idea of using reflection on attributes (see if it does not create duplicates) :wink:, but I'm going to see what went wrong with `Car`.

Let me review the whole thing

**Comment by mertsincan** [comment]
Ok, thanks a lot for the update! How do we find LazySorter.java? Any thought?

**Comment by Rapster** [comment]
I'll show you in a bit :wink:

**Comment by Rapster** [comment]
@mertsincan When you want to include something that can't be deduced from xhtml parsing, then you'll have to explicitely include it like this:
```xml
<ui:define name="more-source-tabs">
    <p:tab title="/org/primefaces/showcase/view/data/datatable/LazySorter.java" />
</ui:define>
```

**Comment by mertsincan** [comment]
Thanks a lot for the refactor! I just changed the order of tabs. I think it's good enough for now.  Maybe, we could find Car.java in List<Car> later. ;) Exp; http://localhost:8080/showcase/ui/data/dataView.xhtml

**Comment by Rapster** [comment]
Mert, is font-awesome has been dropped of PF?

**Comment by mertsincan** [comment]
I removed context-param of FontAwesome in web.xml. But, I'll add it again. We are considering removing it in the jar of the next community version(after 6.3). For Fontawesome, users can add this package; https://mvnrepository.com/artifact/org.webjars/font-awesome

we recommend using the PrimeIcons; https://github.com/primefaces/primeicons

**Comment by Rapster** [comment]
Does it mean that PF will no longer embed font awesome but will be compatible? Or users will have no choice but to move their icons to PrimeIcons

**Comment by mertsincan** [comment]
Please see; https://github.com/primefaces/primefaces/issues/3056#issuecomment-441245147
