### ISSUE TITLE
ExceptionHandler error

### ISSUE THREAD

**Issue by Betlista** [primefaces/showcase-facelift#105]
Hi,

when I open current Showcase nad navigate to ExceptionHandler
https://www.primefaces.org/showcase/ui/misc/exceptionHandler.xhtml

when I click on "Throw ViewExpiredException!" or "Throw NullPointerException!" stack is shown in a dialog.

When I click on "Throw IllegalStateException!" error page is shown - https://www.primefaces.org/showcase/error.xhtml

This is all for Ajax Exception Handler. I'd expect even for the last button to show exception in the dialog.

For non-ajax, I'm not sure actually what should be the behavior, but currently, there is a redirect to the error page for NPE.

**Comment by tandraschko** [comment]
Thats expected as there is no p:ajaxExceptionHandler type="java.lang.IllegalStateException"

**Comment by Betlista** [comment]
Ok, that explains the behavior (for 3rd ajax button), but is that what showcase wanted to show?

Is it also ok for NPE for non-ajax (that it is not "handled")?

**Comment by tandraschko** [comment]
Yes, there is no mapping for NPE in web.xml

**Comment by tandraschko** [comment]
Feel free to improve the text in the showcase and provide a PR!
