### ISSUE TITLE
Development documentation is missing

### ISSUE THREAD

**Issue by jrichardsz** [primefaces/showcase-facelift#11]
Hi Primefaces team.

Current documentation has these items:

- Prebuilt war
- Build from sources
- Run from local sources

But what happens if I want to open this repository with classic ide like:**eclipse**?

I was able to start it using eclipse but several configurations and a specific server were required.

On the other way, Can I contribute to the wiki?

Thanks

Regards,
Richard

**Comment by tandraschko** [comment]
It's just a simple web project - and every IDE handles it different.
There are already much articles on the web, to how run a maven web project from IDE.

So i don't think we need something. There is nothing special in the showcase.

**Comment by jrichardsz** [comment]
Please, can you see this issue?

https://github.com/primefaces/showcase-facelift/issues/12#issuecomment-413625953

This simple web project does not work as others jsf projects.
