### ISSUE TITLE
css is not loaded when app is started using eclipse with tomcat

### ISSUE THREAD

**Issue by jrichardsz** [primefaces/showcase-facelift#12]
## 1) Environment
- PrimeFaces version: Current master branch
- Artifact: war
- Does it work on the newest released PrimeFaces version? : Works using mvn compilation but does not work with eclipse
- Does it work on the newest sources in GitHub?: No
- Operative System: Ubuntu 16.04.1
- Eclipse : Oxygen.1a Release (4.7.1a)
- Tomcat 9 with jdk 8
- Affected browsers: Firefox, Chromiun

## 2) Expected behavior

- clone  https://github.com/primefaces/showcase-facelift.git
- import it on eclipse as maven project
- select **Run on server**. 
- open browser at http://localhost:8080/showcase/
- showcase must be correctly rendered

## 3) Actual behavior

- clone  https://github.com/primefaces/showcase-facelift.git
- import it on eclipse as maven project
- select **Run on server**. 
- open browser at http://localhost:8080/showcase/
- showcase load but css is wrong : https://raw.githubusercontent.com/jrichardsz/static_resources/master/primefaces-issue-css.png

## 4) Steps to reproduce

- Download Eclipse IDE
- Check if maven is configured in eclipse
- Add JDK 8 in **Installed JREs** option (eclipse)
- Clone this repository: https://github.com/primefaces/showcase-facelift.git
- Set **community-stable** profile as default in pom.xml
- Import it on eclipse as maven project
- Perform a maven update in eclipse project
- Add tomcat 9 in **server** section in eclipse.
- select **Run on server**. 
- open browser at http://localhost:8080/showcase/

Thanks

**Comment by tandraschko** [comment]
Can you try to set the executed phase of the maven-sass-plugin to "process-resources"?

**Comment by jrichardsz** [comment]
This was not documented. 

After try some mvn sass commands, this worked : 

```
sass:scss-lint
```
So, total steps required to startup this web application in a development environment are:

- Download Eclipse IDE
- Check if maven is configured in eclipse
- Add JDK 8 in **Installed JREs** option (eclipse)
- Clone this repository: https://github.com/primefaces/showcase-facelift.git
- Set **community-stable** profile as default in pom.xml
- Import it on eclipse as maven project
- Perform a maven update in eclipse project
- Add tomcat 9 in **server** section in eclipse.
- Execute this **mvn** command to prepare css resources : `sass:scss-lint`
- Right click on eclipse project and select **Run as >> Run on server** 
- Open browser at http://localhost:8080/showcase/

I am a madman of automation so I like to test applications in a empty environment and only if it works, some continuous delivery flows could be implemented with jenkins for instance.

JSF lovers, juniors, and seniors would be grateful if a minimal instruction  be providessssd.

Thanks so much.

**Comment by tandraschko** [comment]
Thanks for ignoring my comment :)

**Comment by jrichardsz** [comment]
Sorry.

Your comment pointed me to the solution. 

Thanks.

**Comment by tandraschko** [comment]
Maven should build it automatically via the configured Plugin, therefore i mentioned IT.

**Comment by jrichardsz** [comment]
```
mvn clean package
```
