### ISSUE TITLE
Refused script in mailbox layout if CSP is enabled

### ISSUE THREAD

**Issue by cnsgithub** [primefaces/showcase-facelift#39]
Googly Analytics script is being loaded in `mailbox.xhtml` with javascript:
```javascript
                ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
                var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
```

This gets refused correctly by the browser if `primefaces.CSP` is enabled:
![image](https://user-images.githubusercontent.com/13161711/57122113-deed2800-6d7b-11e9-8920-213a45c3b11c.png)

This is why #8 specified _google-analytics.com_ in `primefaces.csp.ALLOWED_HOSTS` which is no longer available in the new CSP prototype.

We could also delegate the addition of allowed `script-src` hosts to developers/sysadmins, in this case we would have two separated `Content-Security-Policy` headers:

1. Nonce

```
Content-Security-Policy: script-src google-analytics.com
```

2. Host

```
Content-Security-Policy: script-src google-analytics.com
```

However, it depends on the user agent how both `Content-Security-Policy` headers are combined, either by intersecting or unioning them. Not sure how modern browsers behave right now.

You can see the results of the two variants here:
1. Union: https://cspvalidator.org/#headerValue%5B%5D=script-src+'nonce-1234'&headerValue%5B%5D=script-src+google-analytics.com&strategy=union
2. Intersection: https://cspvalidator.org/#headerValue%5B%5D=script-src+'nonce-1234'&headerValue%5B%5D=script-src+google-analytics.com&strategy=intersection

As you can see, intersection will of course result in an empty `script-src` directive which is not the desired behaviour in this case.

We could do several things to solve this:
1. Take care of pre-existing `Content-Security-Policy` headers when setting the header in `CspPhaseListener` and combine them accordingly. There is a nice lib to do this: https://github.com/shapesecurity/salvation. Btw, please also note that there is a difference between `HttpServletResponse.setHeader` (currently used) and `HttpServletResponse.addHeader`.
2. Specify allowed hosts again in `web.xml`.

I would prefer the first approach.

**Comment by cnsgithub** [comment]
Just did a quick test by adding to CSP headers in `CspPhaseListener`:
```java
            response.addHeader("Content-Security-Policy", "script-src 'nonce-" + state.getNonce() + "'");
            response.addHeader("Content-Security-Policy", "script-src www.google-analytics.com");
```

Result in Chrome - second CSP header overrides the first one resulting in refusal of scripts using the nonce:
![image](https://user-images.githubusercontent.com/13161711/57123201-4eb1e180-6d81-11e9-934d-26f2927bf4b1.png)

**Comment by tandraschko** [comment]
i really like 2) a bit more as it doesn't require another library

**Comment by cnsgithub** [comment]
Instead of using domain whitelists, we could also try to always add `strict-dynamic` to the `script-src` directive. It's recommended [here](https://www.owasp.org/images/c/c4/2017-04-20-OWASPNZ-SpagnuoloWeichselbaum.pdf).

https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/script-src#strict-dynamic

**Comment by cnsgithub** [comment]
As mentioned in https://github.com/primefaces/primefaces/issues/3505, using `strict-dynamic` would be an alternative to using whitelist domains. However, since this opens DOM XSS vulnerabilities, we should not use it. But we should not use whitelist domains either. So, maybe we can advice users to refactor the way JS libs like googleanalytics are integrated, e.g. by using `script src="googleanalytics` where `CspResponseWriter` would automatically add a nonce.

**Comment by cnsgithub** [comment]
> So, maybe we can advice users to refactor the way JS libs like googleanalytics are integrated

Maybe like [this](https://developers.google.com/analytics/devguides/collection/analyticsjs/#alternative_async_tracking_snippet)?

**Comment by melloware** [comment]
2 things...

1. I just added the ability to customize your CSP_POLICY here: https://github.com/primefaces/primefaces/issues/5213

2. This example with Mailbox will go away as the Layout component is deprecated and will be removed.  So I don't think we should bother fixing this example and should close this ticket?
