### ISSUE TITLE
move from javax.faces.bean to CDI

### ISSUE THREAD

**Issue by christophs78** [primefaces/showcase-facelift#47]
For people new to JSF it´s confusing to see the old and deprecated JSF-Annotations in the showcase. I think it would help to migrate the showcase to CDI.

**Comment by tandraschko** [comment]
+1

**Comment by christophs78** [comment]
I´ll try to work on this during this summer after we finished our LocalDate/Time-work.

**Comment by tandraschko** [comment]
Thanks!
