### ISSUE TITLE
Provide showcase for testing CSP integration

### ISSUE THREAD

**Issue by cnsgithub** [primefaces/showcase-facelift#6]
A showcase should be added to allow for integration testing of the new CSP features introduced with https://github.com/primefaces/primefaces/pull/3884. 

Some brainstorming:
- use `p:wizard`
- test just one case in every step
- add _Check functionality_ button
- add _Validate CSP_ button (use https://cspvalidator.org/ to actually validate)
- show CSP header
- do some javascript on success, e.g. `alert('PASS');`
- possible steps:
   1. JS event handlers
   2. JS URI handlers
   3. `p:ajax`
   4. `f:ajax`
   5. JS event handlers in partial response
   6. JS URI handlers in partial response
   7. `script` in partial response
   8. `eval` in partial response
   9. pre-existing nonce

I accept this issue myself.

**Comment by cnsgithub** [comment]
@tandraschko @melloware I need some beta testers... :wink:

**Comment by melloware** [comment]
I can hopefully do some testing.  I need to read more about CSP so I fully understand what its doing so I can evaluate what you are doing!  Once again though, I love the work that you are doing to make PF more secure!

**Comment by cnsgithub** [comment]
Committed in f41fd25116a52b0fa9e9d2589e72ade53774dc62.
