### ISSUE TITLE
TimeLine: Add all examples from PFE

### ISSUE THREAD

**Issue by melloware** [primefaces/showcase-facelift#63]
See: https://github.com/primefaces/primefaces/issues/5143

There are many missing examples that were in the old PrimeFaces Extensions version of the Timeline.  Those examples helped explain functionality and how to use the Timeline that are now being reported as bugs because there are missing examples.

**Comment by jasonex7** [comment]
This would an excellent fix. I think this should be done after PR primefaces/primefaces#5113 gets merged.

**Comment by jasonex7** [comment]
The PR to this issue should consider this comment: https://github.com/primefaces/primefaces/issues/5254#issuecomment-544738237
