### ISSUE TITLE
Cross-link documentation and showcase

### ISSUE THREAD

**Issue by christophs78** [primefaces/showcase-facelift#82]
We should provide a link from the showcase-example of each component to the documentation of the component and vice-versa.
I´ll look into this...

**Comment by Rapster** [comment]
Looks good, I think you could have used regex to extract the component "ui/{family}/{component}/{optionalmorestuff}

**Comment by christophs78** [comment]
There is no general rule how to map showcase to docu. Would require some refactoring/restructuring on one of both sides.

**Comment by Rapster** [comment]
It's okay now it's done
